JSON parser
Teaching-projects/SZE-MOSZE-2020-SeGITseg pull request #5
Opened 2020-10-15 12:14 UTC by k-kristof

- Készült egy `JSONParser` nevű osztály, amelyben egy statikus `Parse` metódus istream és string bemenettel is képes JSON forműtumú szövegből map-et alkotni.
- A `Unit` osztály `parseUnit` metódusa már ezt a parsert használja.
- Készült 3 unit teszt is, 1 istream bemenetre, 1 string bemenetre és 1 hibás formátumú bemenetre.

2020-10-18 15:15 UTC, wajzy requested changes
Kritizálható lenne a parzer, mert jól sejtem, akkor megköveteli, hogy egy sorban pontosan egy kulcs-érték pár álljon, ami persze a valóságban nem elvárható egy JSON fájltól. Viszont történtek erőfeszítések néhány lehetséges hiba ellenőrzésére, és ez most nekem elég.
Van viszont pár megjegyzésem, ezeket szeretném, ha figyelembe vennéd, mielőtt elfogadnám a megoldásod.

2020-10-18 15:15 UTC, wajzy commented on jsonparser.h
> +    static std::map<std::string, std::string> Parse(const std::string &iString);
Tudunk tehát folyamból olvasni, és meg lehet adni egy fájl nevét is, még ha a függvény neve nem is nagyon utal erre. Viszont az egyetlen stringben lévő JSON tartalmat még nem tudjuk elemezni.

2020-10-18 15:15 UTC, wajzy commented on test/parser_test.cpp
> +    }
ASSERT_THROW?

2020-10-19 20:55 UTC, k-kristof commented
@wajzy elvégeztem a szükséges módosításokat!

2020-10-24 12:00 UTC, k-kristof commented
@wajzy érdeklődni szeretnék a review állapotáról, mehet-e a conflict feloldás?

2020-10-24 13:17 UTC, wajzy approved these changes
OK.

2020-10-24 13:17 UTC, wajzy commented on test/parser_test.cpp
> +    ASSERT_THROW(JSONParser::ParseStream(invalidInput), std::runtime_error);
Kicsit már sajnálom is, hogy ezt átírattam, mert így meg a hibaüzenetet nem lehet pontosan tesztelni.

2020-10-24 13:18 UTC, wajzy commented
@k-kristof Mehet a conflictok feloldása!

2020-10-24 13:57 UTC, k-kristof commented
@wajzy feloldottam a conflictokat, mergeltem és kiegészítettem a parsert hogy a cooldownt is kezelje.

2020-10-25 07:54 UTC, merged