Levelup
Teaching-projects/SZE-MOSZE-2020-SeGITseg pull request #6
Opened 2020-10-15 14:09 UTC by borosdavid96

2020-10-17 14:13 UTC, oliverosz requested changes
Az észrevételeim javítása után lehet rögtön frissíteni a branchet a masterre, és feloldani a konfliktusokat.

2020-10-17 14:13 UTC, oliverosz commented on .github/workflows/test_workflow.yml
> +        run: g++ -std=c++17 *.cpp
Legyen ott egy `-Wall` meg `-Werror` is.

2020-10-17 14:13 UTC, oliverosz commented on unit.cpp
> +#include <math.h>
`<cmath>`

2020-10-17 14:13 UTC, oliverosz commented on unit.cpp
> +			addXp(dmg);
Itt az ütés előtti hp-nek megfelelő xp-t kellene kapnia.

2020-10-17 14:13 UTC, oliverosz commented on unit.cpp
> +			other.addXp(other.dmg);
Itt is, hála a kódismétlésnek

2020-10-18 19:10 UTC, oliverosz reviewed
Most már rendben van a megoldás, jöhet a konfliktusfeloldás. (rhyme not intended)

2020-10-19 14:21 UTC, borosdavid96 commented
@oliverosz Elvileg sikerült megcsinálni.

2020-10-19 16:11 UTC, oliverosz requested changes

2020-10-19 16:11 UTC, oliverosz commented on unit.cpp
> +	other.addXp(other.dmg);
Az jó, hogy a kódismétlés csökkent az attack függvénnyel, de ez most nem ekvivalens a korábbi verzióval. Ami korábban ki lett javítva, az most megint elromlott: ha az áldozatnak kevesebb élete van, mint a sebzés, akkor csak annyi xp-t kapjon a támadó, amennyi sérülést ténylegesen okozott.

2020-10-19 16:11 UTC, oliverosz commented on unit.cpp
> +			timeB += other.getCd();
Na itt már jó, de ha az első ütés overkill, akkor ott még fennáll a probléma. Igazából az attack függvényben lenne logikus növelni az xp-t, elvégre mindig ezt a logikát kell követni.

2020-10-19 20:52 UTC, borosdavid96 commented
@oliverosz  Remélem sikerült orvosolni.

2020-10-20 13:30 UTC, oliverosz approved these changes
Na így sokkal szebb.

2020-10-20 13:30 UTC, merged